- name: 'Type: Bug'
  color: 'e80c0c'
  description: Something isn't working as expected.
  from_name: 'Bug'

- name: 'Design'
  color: 'FFA07A'
  description: Something isn't working as expected.

- name: 'Database'
  color: 'FBCA04'
  description: Issues related to the database or data storage.

- name: 'Research'
  color: 'C2E0C6'
  description: Issues related to research or investigation of a problem or potential feature.

- name: 'Tech Debt'
  color: 'FBCA04'
  description: Issues related to technical debt, such as refactoring or cleaning up code.

- name: 'Type: Enhancement'
  color: '54b2ff'
  description: Suggest an improvement for an existing feature.
  from_name: 'Enhancement'

- name: 'Type: Feature'
  color: '54b2ff'
  description: Suggest a new feature.
